version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root/0000
      MYSQL_DATABASE: scraping
      MYSQL_USER: root
      MYSQL_PASSWORD: root/0000
    ports:
      - "3300:3300"
